title: Deep Learning Course
tagline: Course website of DL, FUM
description: DL Course website, Fall 2023, Dr. M. Amintoosi
author: M. Amintoosi
baseurl: '/dl-fall2024' # the subpath of your site, e.g. /blog
url: 'https://fum-cs.github.io' # the base hostname & protocol for your site, e.g. http://example.com


aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
